server:
  port: 8081
  error:
    include-message: never

spring:
  datasource:
    url: jdbc:postgresql://46.202.164.251:5432/wdTestDB
    username: postgres
    password: Staygether@2025
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  mail:
    host: smtp.hostinger.com
    port: 465
    username: info@walldotbuilders.com
    password: Staygether@2025
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000

file:
  upload-dir: /var/wd_storage/uploads
storageBasePath: /var/wd_storage/uploads

logging:
  level:
    org.springframework.security: INFO
    com.wd.custapi: INFO

app:
  email:
    enabled: true
  customer-portal-base-url: https://app.walldotbuilders.com
  cors:
    allowed-origins: https://app.walldotbuilders.com,https://www.walldotbuilders.com,https://walldotbuilders.com
